package:
  name: llvm-tapir50
  version: "{{ environ.get('CLANG_LLVM_BUILD_VERSION') }}"

source:
  git_url: https://github.com/wsmoses/Tapir-LLVM
  git_rev: "{{ environ.get('CLANG_LLVM_GIT_HASH') }}"

requirements:
  build:
    - cmake
  run:
    - cmake

build:
  number: {{ environ.get('CLANG_LLVM_BUILD_NUMBER') }}
  skip: True   # [win]

test:
  commands:
    - $PREFIX/bin/llvm-config --libs
    - $PREFIX/bin/llc -version
    - test -f $PREFIX/include/llvm/Pass.h
    - test -f $PREFIX/lib/libLLVMCore.a

    - $PREFIX/bin/clang --version
    - $PREFIX/bin/clang++ --version
    - $PREFIX/bin/clang-check --version
    - test -f $PREFIX/include/clang/Lex/Lexer.h
    - test -f $PREFIX/lib/libclangBasic.a


about:
  home: https://github.com/wsmoses/Tapir-LLVM
  license: NCSA
  summary: Tapir extension to LLVM for optimizing Parallel Programs

extra:
  recipe-maintainers:
    - prigoyal
